import { Big_Shoulders_Stencil_Text, Geist, Geist_Mono, Montserrat,} from "next/font/google";
import "./globals.css";
import Navbar from "./Componets/Navbar/Navbar";
import CursorFlow from "./Componets/CursorFlow/CursorFlow";
import TopUp from "./Componets/TopUp/TopUp";
import Footer from "./Componets/Footer/Footer";
import New from "./Componets/New/New";
import app from "./lib/firebase.config";
import { Bounce, ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ['100','200','300','400','500','600','700','800','900'],
})

export const big = Big_Shoulders_Stencil_Text({
  subsets: ["latin"],
  weight: ['300','400','500','600','700','800','900'],
})

export const metadata = {
  title: "Raiyan - Web Developer",
  description: "Generated by create next app",
  icons: {
    icon: "images/icon.png", // Supports different formats
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gradient-to-br from-[#26282a] via-[#494c4f] to-[#26282a]">
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
          />
          <CursorFlow/>
          <Navbar/>
          {children}
          <New/>
          <Footer/>
          <TopUp/>
        </div>
      </body>
    </html>
  );
}
